
os:
- linux

language: node_js

node_js:
- 8

addons:
  apt:
    packages:
      - libsecret-1-dev

before_install:
- if [ $TRAVIS_OS_NAME == "linux" ]; then
    export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
    sh -e /etc/init.d/xvfb start;
    sleep 3;
  fi

script:
- npm test --silent

before_deploy:
- npm install -g vsce;
- vsce package;

deploy:
- provider: releases
  api_key:
    secure: todo
  file_glob: true
  file: "*.vsix"
  skip_cleanup: true
  on:
	branch: master
    tags: true
    condition: $TRAVIS_OS_NAME = linux

