sudo: false
env:
  global:
    - PACKAGE_VERSION="$(node -p -e 'require(\"./package.json\").version')"
notifications:
  email: false
os:
- linux
language: node_js
node_js:
- 8
addons:
  apt:
    packages:
    - libsecret-1-dev
services:
  - xvfb
before_install:
- if [ $TRAVIS_OS_NAME == "linux" ]; then
    export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
    sleep 3;
  fi
script:
- npm test --silent
- npm run vscode:prepublish
cache:
  directories:
    - .vscode-test
before_deploy:
- npm install -g vsce;
- vsce package;
deploy:
  provider: releases
  api_key:
    secure: XOZxGEzIrxoR4aLM7oKDyri0KP3kKMr3yx98aPZV/oeMNQAn59TeAk/xbxLZgJtUolj4CkTOShK8S8HQVUFda6HivZFcQ68SnVwWIgY09gQC7ivTe0vf0KtrntFQ9yyoS/A68PNon2SEOtlC2yHjfNygOfjafBNXiJCxGmcl0RT4atxDrZu31Igx7Hk594j7JvqqCgel/5w0N4IvnEdDLp8jJB1guzm9TJd6QMYzgKkspkDSHxh+54SIeq9hynobX7cSqHIw2MqaPIDdVtX4HRI6ne1CWE6H3FKozbHwPV1/8MZExe3OrrKeRyu7qFzajdEcItcSEn4uyx+KaGWrv0j6gxJ+kAg5q58yn+jb4/k69lNMA8AIRgfz/ZVPyJHnLnmmHooU8j/N4bjf6/0EqZMzsAh+Fye7rQP3/dBkuL8/oDHFtX3Ci1H3JOBaTSYFlZuT3zGY7DGrjouZtjnmC32n903k+tx1nOsMc8ptjPAiLQxbTje0F0+QopboYDZJU5DRdZM07b1NdPr+y9flVjTfxAj2swYfKUPz+ZKxWjWRsWQTLeBzokCQXp2B3H2/gbozaFJ0JjkAnDB+wkPViVUXCLWCBP/CRI2JREqojdutb8zDrLAHVAbqz3qxtgejmdW3IyOaA30U/2JgKF9vrbHpwi/JEnKftyIN8CAVtZI=
  file_glob: true
  file: "*.vsix"
  skip_cleanup: true
  name: "Version ${PACKAGE_VERSION}"
  on:
    repo: decoda/erlang-symbols
    branch: master
    tags: true
    condition: $TRAVIS_OS_NAME = linux
